---
# vim: set ft=ansible:
#
# Unlocks the system to be unlocked to make permanent changes to the /usr mount
#
- name: Unlock system with hotfix
  command: ostree admin unlock --hotfix

- include_role:
    name: rpm_ostree_status

- name: Fail if unlocked is not set to hotfix
  when: "'hotfix' not in ros_booted['unlocked']"
  fail:
    msg: "Unlock is not set to hotfix"
