---
# vim: set ft=ansible:
#
# This is a copy of the `docker_pull_run_remove` role which has been adapted
# to use `podman`.  There are some minor changes that expand on the original
# role to make this more comprehensive.
#
# `popular_images` is defined in roles/podman_pull_run_remove/vars/main.yml
# It is a dict using image names as a key and the value is a command that
# can be run.
#

# Check to see if the host has podman, but don't fail if it is not installed
- name: Check if podman is installed
  command: rpm -q podman
  register: podman
  ignore_errors: true

- when: "'CentOS' not in ansible_distribution"
  set_fact:
    pull_images: "{{ popular_images | combine(rhel_images) }}"

- when: "'CentOS' in ansible_distribution"
  set_fact:
    pull_images: "{{ popular_images }}"

- when: podman.rc == 0
  block:
    - name: Disable the docker daemon
      service:
        name: docker
        state: stopped

    - name: Pull the popular container images
      command: "podman pull {{ item.key }}"
      with_dict: "{{ pull_images }}"
      register: podman_pull
      retries: 5
      delay: 60
      until: podman_pull is success

    - name: Run the popular container images
      command: "podman run --rm {{ item.key }} echo 'hello'"
      with_dict: "{{ pull_images }}"

    # Test for https://bugzilla.redhat.com/show_bug.cgi?id=1585735
    - name: Run the popular container images with cpu-shares flag
      command: "podman run --cpu-shares 2 --rm {{ item.key }} echo 'hello'"
      with_dict: "{{ pull_images }}"

    # Test for https://bugzilla.redhat.com/show_bug.cgi?id=1592932
    #          https://bugzilla.redhat.com/show_bug.cgi?id=1593419
    - name: Run the popular container images testing for network access
      command: "podman run --rm {{ item.key }} {{ item.value }}"
      with_dict: "{{ pull_images }}"

    # Test for https://bugzilla.redhat.com/show_bug.cgi?id=1650512
    - name: Run popular images as detached
      command: "podman run --name test-{{ item.split('/')[-1] }} -d {{ item }} sleep 1000"
      with_items: "{{ pull_images }}"

    - name: Exec into the daemon containers
      command: "podman exec test-{{ item.split('/')[-1] }} date"
      with_items: "{{ pull_images }}"

    - name: Cleanup containers
      command: "podman rm -f test-{{ item.split('/')[-1] }}"
      with_items: "{{ pull_images }}"

    - name: Remove the popular container images
      command: "podman rmi {{ item.key }}"
      with_dict: "{{ pull_images }}"

    - name: Re-enable docker
      service:
        name: docker
        state: started
