---
# vim: set ft=ansible:
# role: rpm_ostree_install_verify
#
# This role verifies that a package is installed after rpm-ostree install
#  by checking the package name is in rpm-ostree status output and verifying
#  that the binary is available by using which.
#
# Parameter:
#   roiv_package_name - name of a single package
#   roiv_binary_name - name of binary to check for (optional)
#   roiv_status_check - boolean - optionally check the rpm-ostree status for package
#
# Requirements:
#  This role must be run after the reboot following rpm-ostree install of a package
#
# !!! WARNING!!!
#   If you plan on using this role multiple times in a playbook, you should
#   explicitly provide values for 'roiv_package_name' and 'roiv_binary_name'
#   in order to avoid existing values in the playbook namespace to be reused
#   across the roles.
#
- name: Fail if no package specified
  when: roiv_package_name is undefined
  fail:
    msg: "No packages specified"

# The 'binary' fact can be set to something other than the package name
# if needed
- name: Setup binary fact
  set_fact:
    roiv_binary_name: "{{ roiv_binary_name if roiv_binary_name is defined else roiv_package_name }}"
    roiv_status_check: "{{ roiv_status_check | default(true) }}"

- include_role:
    name: rpm_ostree_status

# ros_booted is pulled from the rpm_ostree_status role above
- name: Fail if {{ roiv_package_name }} is not in list of installed packages
  when: roiv_package_name not in ros_booted['packages'] and
        roiv_status_check
  fail:
    msg: |
      {{ roiv_package_name }} is not in rpm-ostree status output
      Result: {{ ros_booted['packages'] }}

- name: Check for {{ roiv_binary_name }} binary
  command: command -v {{ roiv_binary_name }}

- name: Check {{ roiv_package_name }} in rpmdb
  command: rpm -q {{ roiv_package_name }}
